// Agent loop: works this repo's agent queue with Sandcastle, forever or once.
//
//   npm run agents                    loop: plan autopilot epics, work every
//                                     ready ticket, sleep when idle
//   npm run agents -- --once          one pass, then exit
//   npm run agents -- --no-planning   build only: leave epic planning to others
//
// Planning only touches epics labelled `autopilot` (chosen at the end of their
// /brief): chart and resolve their wayfinder map, write the spec for your
// review, and cut tickets once you approve it. Other epics are planned by hand.
//
// One pass:
//   1. Queue: open, unassigned, unblocked issues labelled ready-for-agent or
//      ready-for-agent-debugging. Specs are skipped (they're read by
//      /to-tickets, never built directly).
//   2. Plan: an agent picks the tickets that can safely run in parallel.
//   3. Claim each one (assignee = claimed), prepare its branch: tickets under
//      an epic branch off the epic branch, after `main` is merged into it;
//      the others branch off `main`.
//   4. Execute + review: one Docker sandbox per ticket, running /implement or
//      /debug-and-fix, then a review pass.
//   5. Land: epic tickets merge into the epic branch and close; the others
//      get a PR with "Fixes #n". An epic with no open tickets left gets its
//      PR to main ("Closes #epic").
//   6. Verify: an epic PR whose milestone is empty is checked with
//      /verify-epic, once per commit; its failures become tickets that the
//      next pass picks up, and its status feeds the epic-gate merge check.
//
// Adapted from Sandcastle's parallel-planner-with-review template
// (https://github.com/mattpocock/sandcastle, MIT).

import * as sandcastle from "@ai-hero/sandcastle";
import { docker } from "@ai-hero/sandcastle/sandboxes/docker";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync } from "node:fs";
import { setTimeout as sleep } from "node:timers/promises";
import { z } from "zod";

// ---------------------------------------------------------------------------
// Configuration (env overrides, e.g. in .sandcastle/.env or the shell)
// ---------------------------------------------------------------------------

const ONCE = process.argv.includes("--once");
const PLANNING = !process.argv.includes("--no-planning");
const IDLE_MINUTES = Number(process.env.AGENTS_IDLE_MINUTES ?? 45);
const LIMIT_SLEEP_MINUTES = Number(process.env.AGENTS_LIMIT_SLEEP_MINUTES ?? 60);
const MAX_PARALLEL = Number(process.env.AGENTS_MAX_PARALLEL ?? 3);
const PLANNER = process.env.AGENTS_PLANNER_MODEL ?? "claude-opus-5-5";
const WORKER = process.env.AGENTS_WORKER_MODEL ?? "claude-sonnet-5";
const ALERTS = process.env.SLACK_ALERTS_WEBHOOK_URL;
const LABEL = {
  build: process.env.AGENTS_LABEL_BUILD ?? "ready-for-agent",
  bug: process.env.AGENTS_LABEL_BUG ?? "ready-for-agent-debugging",
  human: process.env.AGENTS_LABEL_HUMAN ?? "ready-for-human",
  review: process.env.AGENTS_LABEL_REVIEW ?? "ready-for-review",
  epic: "epic",
  spec: "spec",
  approved: "spec-approved",
  map: "wayfinder:map",
  planning: "agent:planning",
  autopilot: "autopilot",
  briefing: "needs-briefing",
};
const AI_NOTE = "> *This was generated by AI";
const WORKTREES = ".sandcastle/worktrees";

const hooks = { sandbox: { onSandboxReady: [{ command: "npm install" }] } };
const copyToWorktree = ["node_modules"];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type Epic = { number: number; title: string; branch: string; milestone: string };
type Ticket = { number: number; title: string; kind: "build" | "bug"; epic?: Epic; branch: string };

const sh = (cmd: string, args: string[], cwd?: string) =>
  execFileSync(cmd, args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
const gh = (...args: string[]) => sh("gh", args);
const ghJson = <T,>(...args: string[]): T => JSON.parse(gh(...args));
const git = (cwd: string | undefined, ...args: string[]) => sh("git", args, cwd);
const tryGit = (cwd: string | undefined, ...args: string[]) => {
  try {
    git(cwd, ...args);
    return true;
  } catch {
    return false;
  }
};
const log = (msg: string) => console.log(`[agents ${new Date().toISOString()}] ${msg}`);
const repo = gh("repo", "view", "--json", "nameWithOwner", "--jq", ".nameWithOwner");
const me = gh("api", "user", "--jq", ".login");

async function alert(text: string) {
  log(text);
  if (!ALERTS) return;
  await fetch(ALERTS, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text: `[${repo}] ${text}` }),
  }).catch(() => {});
}

function comment(n: number, body: string) {
  gh("issue", "comment", String(n), "--body", `> *This was generated by AI in the agent loop.*\n\n${body}`);
}

// A spec (from /to-spec) describes work that /to-tickets turns into tickets.
function isSpec(labels: string[], body: string) {
  return labels.includes(LABEL.spec) || (/^## Problem Statement/m.test(body) && /^## User Stories/m.test(body));
}

const epicCache = new Map<string, Epic | undefined>();

// Everything under an epic carries the epic's milestone, so the milestone
// finds the epic even when a ticket isn't linked as its sub-issue.
function epicFor(milestone?: string): Epic | undefined {
  if (!milestone) return undefined;
  if (epicCache.has(milestone)) return epicCache.get(milestone);
  const [epic] = ghJson<{ number: number; title: string; body: string }[]>(
    "issue", "list", "--state", "open", "--label", LABEL.epic, "--milestone", milestone,
    "--json", "number,title,body", "--limit", "1",
  );
  const branch = epic?.body.match(/`(epic\/[^`]+)`/)?.[1];
  const found = epic && branch ? { number: epic.number, title: epic.title, branch, milestone } : undefined;
  epicCache.set(milestone, found);
  return found;
}

function readyTickets(): Ticket[] {
  const tickets: Ticket[] = [];
  for (const kind of ["build", "bug"] as const) {
    const issues = ghJson<{ number: number; title: string; body: string; labels: { name: string }[]; milestone: { title: string } | null }[]>(
      "issue", "list", "--state", "open", "--label", LABEL[kind], "--search", "no:assignee sort:created-asc",
      "--json", "number,title,body,labels,milestone", "--limit", "100",
    );
    for (const issue of issues) {
      const labels = issue.labels.map((l) => l.name);
      if (isSpec(labels, issue.body) || labels.includes(LABEL.epic)) continue;
      const blocked = Number(gh("api", `repos/${repo}/issues/${issue.number}`, "--jq", ".issue_dependencies_summary.blocked_by // 0"));
      if (blocked > 0) continue;
      const epic = epicFor(issue.milestone?.title);
      tickets.push({
        number: issue.number,
        title: issue.title,
        kind,
        epic,
        branch: epic ? `agent/issue-${issue.number}` : `${kind === "bug" ? "fix" : "feat"}/${issue.number}`,
      });
    }
  }
  return tickets;
}

// Assignment means claimed. Two loops (the always-on machine and a laptop)
// can race: claim, re-read, and back off if someone else got there too.
function claim(t: Ticket) {
  gh("issue", "edit", String(t.number), "--add-assignee", "@me");
  const assignees = ghJson<string[]>("issue", "view", String(t.number), "--json", "assignees", "--jq", "[.assignees[].login]");
  if (assignees.length === 1 && assignees[0] === me) return true;
  gh("issue", "edit", String(t.number), "--remove-assignee", "@me");
  return false;
}

function release(t: Ticket, why: string) {
  gh("issue", "edit", String(t.number), "--remove-assignee", "@me");
  log(`#${t.number} released: ${why}`);
}

// The epic branch lives in its own worktree, so the main checkout is never
// switched underneath you. Returns the worktree path, or undefined when the
// epic can't be worked this pass.
function prepareEpic(epic: Epic): string | undefined {
  const path = `${WORKTREES}/${epic.branch.replaceAll("/", "-")}`;
  git(undefined, "fetch", "--quiet", "origin");
  const remote = tryGit(undefined, "rev-parse", "--verify", "--quiet", `origin/${epic.branch}`);
  if (!existsSync(path)) {
    mkdirSync(WORKTREES, { recursive: true });
    if (remote) git(undefined, "worktree", "add", "-B", epic.branch, path, `origin/${epic.branch}`);
    else git(undefined, "worktree", "add", "-b", epic.branch, path, "origin/main");
  } else if (remote) {
    git(path, "merge", "--ff-only", "--quiet", `origin/${epic.branch}`);
  }
  if (!tryGit(path, "merge", "--no-edit", "--quiet", "origin/main")) {
    tryGit(path, "merge", "--abort");
    conflictTicket(epic);
    return undefined;
  }
  git(path, "push", "--quiet", "-u", "origin", epic.branch);
  return path;
}

function conflictTicket(epic: Epic) {
  const title = `Resolve conflicts between ${epic.branch} and main`;
  const open = ghJson<unknown[]>("issue", "list", "--state", "open", "--search", `in:title "${title}"`, "--json", "number");
  if (open.length) return;
  gh("issue", "create", "--title", title, "--label", LABEL.human, "--milestone", epic.milestone, "--body",
    `> *This was generated by AI in the agent loop.*\n\nMerging \`main\` into \`${epic.branch}\` conflicts. The loop skips this epic until the conflicts are resolved on the epic branch.\n\nPart of #${epic.number}.`);
  void alert(`Epic #${epic.number} paused: ${epic.branch} conflicts with main.`);
}

function prepareBranch(t: Ticket, epicPath?: string) {
  if (tryGit(undefined, "rev-parse", "--verify", "--quiet", t.branch)) return; // keep earlier progress
  git(undefined, "branch", t.branch, epicPath ? t.epic!.branch : "origin/main");
}

// ---------------------------------------------------------------------------
// One pass
// ---------------------------------------------------------------------------

const planSchema = z.object({ issues: z.array(z.object({ number: z.number() })) });

async function pass(): Promise<number> {
  epicCache.clear();
  const planned = PLANNING ? await planEpics() : 0;
  const ready = readyTickets();
  if (!ready.length) return planned + (await verifyEpics());

  const plan = await sandcastle.run({
    hooks,
    sandbox: docker(),
    name: "planner",
    maxIterations: 1,
    agent: sandcastle.claudeCode(PLANNER),
    promptFile: "./.sandcastle/plan-prompt.md",
    promptArgs: {
      MAX_PARALLEL: String(MAX_PARALLEL),
      TICKETS: ready.map((t) => `- #${t.number} (${t.kind}${t.epic ? `, epic #${t.epic.number}` : ""}): ${t.title}`).join("\n"),
    },
    output: sandcastle.Output.object({ tag: "plan", schema: planSchema }),
  });
  const picked = planSchema.parse(plan.output).issues
    .map((p) => ready.find((t) => t.number === p.number))
    .filter((t): t is Ticket => !!t)
    .slice(0, MAX_PARALLEL);

  const epicPaths = new Map<number, string | undefined>();
  const work: { t: Ticket; epicPath?: string }[] = [];
  for (const t of picked) {
    if (t.epic && !epicPaths.has(t.epic.number)) epicPaths.set(t.epic.number, prepareEpic(t.epic));
    const epicPath = t.epic ? epicPaths.get(t.epic.number) : undefined;
    if (t.epic && !epicPath) continue; // epic paused on a conflict with main
    if (!claim(t)) continue;
    prepareBranch(t, epicPath);
    work.push({ t, epicPath });
  }
  log(`working ${work.map(({ t }) => `#${t.number}`).join(", ") || "nothing"}`);

  const settled = await Promise.allSettled(
    work.map(async ({ t }) => {
      const box = await sandcastle.createSandbox({ branch: t.branch, sandbox: docker(), hooks, copyToWorktree });
      try {
        const done = await box.run({
          name: `#${t.number}`,
          maxIterations: 100,
          agent: sandcastle.claudeCode(WORKER),
          promptFile: t.kind === "bug" ? "./.sandcastle/bug-prompt.md" : "./.sandcastle/implement-prompt.md",
          promptArgs: { ISSUE: String(t.number), TITLE: t.title, BRANCH: t.branch },
        });
        if (!done.commits.length) return 0;
        const review = await box.run({
          name: `#${t.number} review`,
          maxIterations: 1,
          agent: sandcastle.claudeCode(WORKER),
          promptFile: "./.sandcastle/review-prompt.md",
          promptArgs: { ISSUE: String(t.number), BRANCH: t.branch, BASE: t.epic ? `origin/${t.epic.branch}` : "origin/main" },
        });
        return done.commits.length + review.commits.length;
      } finally {
        await box.close();
      }
    }),
  );

  for (const [i, outcome] of settled.entries()) {
    const { t, epicPath } = work[i]!;
    if (outcome.status === "rejected") {
      const reason = String(outcome.reason);
      release(t, reason);
      if (/usage limit|rate limit|429/i.test(reason)) throw new Error(`usage limit: ${reason}`);
      continue;
    }
    if (!outcome.value) {
      // No commits: a bug diagnosed for a person / not reproducible, or a
      // build the agent couldn't finish. The agent has commented; make sure a
      // person sees it.
      const labels = ghJson<string[]>("issue", "view", String(t.number), "--json", "labels", "--jq", "[.labels[].name]");
      if (labels.includes(LABEL[t.kind])) {
        gh("issue", "edit", String(t.number), "--remove-label", LABEL[t.kind], "--add-label", LABEL.human);
      }
      release(t, "no commits; handed to a person");
      continue;
    }
    land(t, epicPath);
  }

  return planned + work.length + (await verifyEpics());
}

function land(t: Ticket, epicPath?: string) {
  if (t.epic && epicPath) {
    if (!tryGit(epicPath, "merge", "--no-edit", "--quiet", t.branch)) {
      tryGit(epicPath, "merge", "--abort");
      comment(t.number, `The work on \`${t.branch}\` conflicts with \`${t.epic.branch}\`; the loop will retry it on top of the latest epic branch.`);
      git(undefined, "branch", "-D", t.branch);
      release(t, "merge conflict with the epic branch");
      return;
    }
    git(epicPath, "push", "--quiet", "origin", t.epic.branch);
    const sha = git(epicPath, "rev-parse", "--short", "HEAD");
    gh("issue", "close", String(t.number), "--comment",
      `> *This was generated by AI in the agent loop.*\n\nLanded on \`${t.epic.branch}\` in ${sha}. It ships with the epic's PR (#${t.epic.number}).`);
    git(undefined, "branch", "-D", t.branch);
    log(`#${t.number} landed on ${t.epic.branch}`);
    return;
  }
  git(undefined, "push", "--quiet", "-u", "origin", t.branch);
  const url = gh("pr", "create", "--base", "main", "--head", t.branch, "--title", t.title, "--body",
    `Fixes #${t.number}\n\n> *This was generated by AI in the agent loop.* See the issue for the reasoning and evidence.`);
  gh("issue", "edit", String(t.number), "--remove-label", LABEL[t.kind], "--add-label", LABEL.review);
  log(`#${t.number} → ${url}`);
}

// ---------------------------------------------------------------------------
// Autopilot planning (epics labelled `autopilot`)
// ---------------------------------------------------------------------------

type Issue = { number: number; title: string; state: string; body: string; labels: { name: string }[]; comments?: { body: string }[] };
type PlanJob = { epic: Epic; kind: "chart" | "work" | "revise" | "tickets"; map?: number; spec?: number };

const has = (i: Issue, label: string) => i.labels.some((l) => l.name === label);

// What each autopilot epic needs next. Epics without the `autopilot` label,
// or still waiting for their brief, are planned by hand and never touched.
function planJobs(): PlanJob[] {
  const epics = ghJson<Issue[]>("issue", "list", "--state", "open", "--label", LABEL.epic, "--label", LABEL.autopilot, "--json", "number,title,state,body,labels", "--limit", "100");
  const jobs: PlanJob[] = [];
  for (const e of epics) {
    if (has(e, LABEL.planning) || has(e, LABEL.briefing)) continue; // another loop is on it, or no brief yet
    const milestone = ghJson<{ milestone: { title: string } | null }>("issue", "view", String(e.number), "--json", "milestone").milestone?.title;
    const branch = e.body.match(/`(epic\/[^`]+)`/)?.[1];
    if (!milestone || !branch) continue;
    if (Number(gh("api", `repos/${repo}/issues/${e.number}`, "--jq", ".issue_dependencies_summary.blocked_by // 0")) > 0) continue;
    const epic = { number: e.number, title: e.title, branch, milestone };
    const items = ghJson<Issue[]>("issue", "list", "--state", "all", "--milestone", milestone, "--json", "number,title,state,body,labels,comments", "--limit", "300")
      .filter((i) => i.number !== e.number);
    const specs = items.filter((i) => i.state === "OPEN" && isSpec(i.labels.map((l) => l.name), i.body));
    const maps = items.filter((i) => has(i, LABEL.map));
    const openMap = maps.find((m) => m.state === "OPEN");

    const spec = specs[0];
    if (spec) {
      if (has(spec, LABEL.approved)) jobs.push({ epic, kind: "tickets", spec: spec.number });
      else if (has(spec, LABEL.human) && !(spec.comments?.at(-1)?.body ?? AI_NOTE).startsWith(AI_NOTE))
        jobs.push({ epic, kind: "revise", spec: spec.number, map: maps[0]?.number });
      continue; // otherwise the spec waits for its review
    }
    if (openMap) {
      jobs.push({ epic, kind: "work", map: openMap.number });
      continue;
    }
    if (!maps.length && !items.length) jobs.push({ epic, kind: "chart" }); // untouched epic
  }
  return jobs;
}

function instructions(j: PlanJob): string {
  const wayfinder = "Read `.claude/skills/wayfinder/SKILL.md` and `.claude/skills/wayfinder/AUTOPILOT.md` and follow them";
  switch (j.kind) {
    case "chart":
      return `Plan epic #${j.epic.number} (${j.epic.title}) on autopilot. ${wayfinder}: chart the map from the epic and its Brief, resolve it, and hand off the spec for review.`;
    case "work":
      return `Continue map #${j.map} of epic #${j.epic.number} on autopilot. ${wayfinder}: resolve the open decisions, and hand off the spec for review when the way is clear.`;
    case "revise":
      return `The spec #${j.spec} of epic #${j.epic.number} has review comments. ${wayfinder}, following the Revise section for spec #${j.spec}${j.map ? ` and map #${j.map}` : ""}.`;
    case "tickets":
      return `The spec #${j.spec} of epic #${j.epic.number} is approved. Read \`.claude/skills/to-tickets/SKILL.md\` and follow it for spec #${j.spec}: publish the tickets with \`ready-for-agent\` in milestone "${j.epic.milestone}". Then remove \`ready-for-human\` from the spec, comment (starting with the AI disclaimer) the tickets created, and close the spec.`;
  }
}

async function planEpics(): Promise<number> {
  for (const [name, color] of [[LABEL.spec, "c5def5"], [LABEL.approved, "0e8a16"], [LABEL.planning, "fbca04"]] as const) {
    try { gh("label", "create", name, "--color", color, "--force"); } catch { /* exists */ }
  }
  const jobs = planJobs().slice(0, MAX_PARALLEL);
  if (!jobs.length) return 0;
  log(`planning ${jobs.map((j) => `#${j.epic.number} (${j.kind})`).join(", ")}`);

  const runs = jobs.map(async (j) => {
    gh("issue", "edit", String(j.epic.number), "--add-label", LABEL.planning);
    try {
      const epicPath = prepareEpic(j.epic);
      if (!epicPath) return;
      const branch = `agent/plan-${j.epic.number}`;
      git(undefined, "branch", "-f", branch, j.epic.branch);
      const box = await sandcastle.createSandbox({ branch, sandbox: docker(), hooks, copyToWorktree });
      let commits = 0;
      try {
        const done = await box.run({
          name: `plan #${j.epic.number}`,
          maxIterations: 1,
          agent: sandcastle.claudeCode(PLANNER),
          promptFile: "./.sandcastle/autopilot-prompt.md",
          promptArgs: { INSTRUCTIONS: instructions(j), BRANCH: branch, EPIC_BRANCH: j.epic.branch },
        });
        commits = done.commits.length;
      } finally {
        await box.close();
      }
      if (commits && tryGit(epicPath, "merge", "--no-edit", "--quiet", branch)) git(epicPath, "push", "--quiet", "origin", j.epic.branch);
      else if (commits) tryGit(epicPath, "merge", "--abort");
      git(undefined, "branch", "-D", branch);

      // A spec now waiting for review: tell the human.
      const [spec] = ghJson<Issue[]>("issue", "list", "--state", "open", "--milestone", j.epic.milestone, "--label", LABEL.spec, "--json", "number,title,state,body,labels", "--limit", "5")
        .filter((i) => has(i, LABEL.human) && !has(i, LABEL.approved));
      if (spec && j.kind !== "tickets") {
        await alert(`Spec ready for review: #${spec.number} ${spec.title} (epic #${j.epic.number}). Add the spec-approved label to approve, or comment what to change.`);
      }
    } finally {
      gh("issue", "edit", String(j.epic.number), "--remove-label", LABEL.planning);
    }
  });
  const settled = await Promise.allSettled(runs);
  for (const [i, outcome] of settled.entries()) {
    if (outcome.status === "rejected") {
      const reason = String(outcome.reason);
      if (/usage limit|rate limit|429/i.test(reason)) throw new Error(`usage limit: ${reason}`);
      await alert(`Planning epic #${jobs[i]!.epic.number} failed: ${reason.slice(0, 300)}`);
    }
  }
  return jobs.length;
}

// An epic is done building when nothing in its milestone is open except the
// epic itself. Then its PR to main goes up (once), and every new commit on it
// is verified once. Returns the number of verifications run.
async function verifyEpics(): Promise<number> {
  const epics = ghJson<{ number: number; title: string; body: string; milestone: { title: string } | null }[]>(
    "issue", "list", "--state", "open", "--label", LABEL.epic, "--json", "number,title,body,milestone", "--limit", "100",
  );
  let ran = 0;
  for (const e of epics) {
    const branch = e.body.match(/`(epic\/[^`]+)`/)?.[1];
    const milestone = e.milestone?.title;
    if (!branch || !milestone || !tryGit(undefined, "ls-remote", "--exit-code", "--heads", "origin", branch)) continue;
    const open = ghJson<{ number: number }[]>("issue", "list", "--state", "open", "--milestone", milestone, "--json", "number", "--limit", "200")
      .filter((i) => i.number !== e.number);
    if (open.length) continue;

    let [pr] = ghJson<{ number: number; headRefOid: string }[]>("pr", "list", "--state", "open", "--head", branch, "--json", "number,headRefOid");
    if (!pr) {
      const url = gh("pr", "create", "--base", "main", "--head", branch, "--title", e.title, "--body",
        `Closes #${e.number}\n\nEvery ticket in milestone **${milestone}** is done. Verification runs next.`);
      log(`epic #${e.number} complete → ${url}`);
      [pr] = ghJson<{ number: number; headRefOid: string }[]>("pr", "list", "--state", "open", "--head", branch, "--json", "number,headRefOid");
      if (!pr) continue;
    }
    const verified = gh("api", `repos/${repo}/commits/${pr.headRefOid}/status`, "--jq", '[.statuses[] | select(.context=="verify-epic")][0].state // ""');
    if (verified === "success" || verified === "failure") continue; // this commit is done

    const verifyBranch = `agent/verify-${e.number}`;
    git(undefined, "fetch", "--quiet", "origin", branch);
    git(undefined, "branch", "-f", verifyBranch, `origin/${branch}`);
    log(`verifying epic #${e.number} (PR #${pr.number} at ${pr.headRefOid.slice(0, 7)})`);
    await sandcastle.run({
      hooks,
      sandbox: docker(),
      name: `verify #${e.number}`,
      maxIterations: 1,
      branchStrategy: { type: "branch", branch: verifyBranch },
      agent: sandcastle.claudeCode(WORKER),
      promptFile: "./.sandcastle/verify-prompt.md",
      promptArgs: { PR: String(pr.number), EPIC: String(e.number), SHA: pr.headRefOid, BRANCH: verifyBranch },
    });
    ran++;
  }
  return ran;
}

// ---------------------------------------------------------------------------
// Loop
// ---------------------------------------------------------------------------

let limitAlerted = false;
for (;;) {
  let worked = 0;
  try {
    worked = await pass();
    limitAlerted = false;
  } catch (error) {
    const message = String(error);
    if (/usage limit|rate limit|429/i.test(message)) {
      if (!limitAlerted) await alert(`Usage limit reached; the agent loop sleeps ${LIMIT_SLEEP_MINUTES} min and retries.`);
      limitAlerted = true;
      if (ONCE) break;
      await sleep(LIMIT_SLEEP_MINUTES * 60_000);
      continue;
    }
    await alert(`Agent loop pass failed: ${message.slice(0, 500)}`);
    if (ONCE) process.exit(1);
  }
  if (ONCE) break;
  if (!worked) {
    log(`nothing ready; sleeping ${IDLE_MINUTES} min`);
    await sleep(IDLE_MINUTES * 60_000);
  }
}
